version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-jenkins
    environment:
      POSTGRES_DB: jenkins_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"